const MOCK_DATA = {
  secciones: [
    { id: 's1', name: 'Piqueos',  slug: 'piqueos',  sort_order: 1, is_active: true },
    { id: 's2', name: 'Entradas', slug: 'entradas', sort_order: 2, is_active: true },
    { id: 's3', name: 'Fondos',   slug: 'fondos',   sort_order: 3, is_active: true },
    { id: 's4', name: 'Cócteles', slug: 'cocteles', sort_order: 4, is_active: true },
  ],
  blocks: [
    // Piqueos
    { id:'b1',  section_id:'s1', item_id:'i1',  block_type:'hero_video',       sort_order:1, badge_text:null,        title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i1',  name:'Yuca Rellena',     price:12900, description:'Yuca rellena de mariscos salteados y ají amarillo.',                                  image_url:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=85', video_url:null, tags:['Firma'],            alergenos:[],                    calorias:null, disponible_desde:null,     disponible_hasta:null     }},
    { id:'b2',  section_id:'s1', item_id:'i2',  block_type:'small_card',        sort_order:2, badge_text:null,        title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i2',  name:'Chicken Fingers',  price:8900,  description:'Tiras de pollo apanadas con panko.',                                                  image_url:'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&q=85', video_url:null, tags:[],                   alergenos:['gluten'],            calorias:380,  disponible_desde:null,     disponible_hasta:null     }},
    { id:'b3',  section_id:'s1', item_id:'i3',  block_type:'small_card',        sort_order:3, badge_text:'Popular',   title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i3',  name:'Yuca Frita',       price:5900,  description:'Yuca crocante con salsa huancaína.',                                                  image_url:'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=85', video_url:null, tags:[],                   alergenos:[],                    calorias:290,  disponible_desde:null,     disponible_hasta:null     }},
    { id:'b4',  section_id:'s1', item_id:'i4',  block_type:'horizontal_banner', sort_order:4, badge_text:null,        title_override:null, subtitle_override:'Rellenas con pulpa de cangrejo', is_active:true, item:{ id:'i4',  name:'Empanadas del Mar', price:9900, description:'Fritas, rellenas de mariscos y ají amarillo.',                                       image_url:'https://images.unsplash.com/photo-1624397640148-949b1732bb0a?w=400&q=85', video_url:null, tags:[],                   alergenos:['gluten','mariscos'], calorias:null, disponible_desde:null,     disponible_hasta:null     }},
    // Entradas
    { id:'b5',  section_id:'s2', item_id:'i5',  block_type:'recommended_card',  sort_order:1, badge_text:'Signature', title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i5',  name:'Ceviche Clásico',  price:15900, description:'Pescado fresco en leche de tigre, choclo, cancha y ají limo.',                       image_url:'https://images.unsplash.com/photo-1535400255456-984e0a4bad35?w=600&q=85', video_url:null, tags:['Fresco','Pescado'], alergenos:['pescado'],           calorias:210,  disponible_desde:null,     disponible_hasta:null     }},
    { id:'b6',  section_id:'s2', item_id:'i6',  block_type:'masonry_image',     sort_order:2, badge_text:null,        title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i6',  name:'Ceviche Apaltado', price:16900, description:'Palta, mango, langostinos y leche de tigre.',                                         image_url:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=85', video_url:null, tags:['Nuevo'],            alergenos:['mariscos'],          calorias:null, disponible_desde:null,     disponible_hasta:null     }},
    { id:'b7',  section_id:'s2', item_id:'i7',  block_type:'masonry_image',     sort_order:3, badge_text:null,        title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i7',  name:'Causa de Pollo',   price:12900, description:'Papa amarilla con ají amarillo y pollo.',                                             image_url:'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=400&q=85', video_url:null, tags:[],                   alergenos:[],                    calorias:320,  disponible_desde:null,     disponible_hasta:null     }},
    // Fondos
    { id:'b8',  section_id:'s3', item_id:'i8',  block_type:'large_card',        sort_order:1, badge_text:'Top 1',     title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i8',  name:'Lomo Saltado',     price:19900, description:'Lomo fino al wok con cebolla, tomate y ají amarillo. Arroz y papas fritas.',        image_url:'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&q=85', video_url:null, tags:['Clásico'],          alergenos:['soya'],              calorias:650,  disponible_desde:null,     disponible_hasta:null     }},
    // Cócteles
    { id:'b9',  section_id:'s4', item_id:'i9',  block_type:'hero_video',        sort_order:1, badge_text:'Ícono',     title_override:null, subtitle_override:'El clásico peruano de autor',    is_active:true, item:{ id:'i9',  name:'Pisco Sour',       price:8500,  description:'Pisco quebranta, limón de pica, jarabe de goma y clara.',                           image_url:'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=85', video_url:null, tags:['Pisco'],            alergenos:['huevo'],             calorias:null, disponible_desde:'18:00:00', disponible_hasta:'23:59:00' }},
    { id:'b10', section_id:'s4', item_id:'i10', block_type:'small_card',        sort_order:2, badge_text:'Nuevo',     title_override:null, subtitle_override:null,                              is_active:true, item:{ id:'i10', name:'Maracuyá Sour',    price:8900,  description:'Pisco con maracuyá fresco y espuma de clara.',                                      image_url:'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=85', video_url:null, tags:[],                   alergenos:['huevo'],             calorias:null, disponible_desde:'18:00:00', disponible_hasta:'23:59:00' }},
  ]
};
